spring:
  datasource:
    url: jdbc:mysql://localhost:3306/r102?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: uniCore7587!
